### PR TITLE
[PKG-3014] jinjasql2 0.1.11 :snowflake:

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Changelog: https://github.com/pythonutilities/jinjasql/releases
License: https://github.com/pythonutilities/jinjasql/blob/0.1.11/LICENSE
Requirements: https://github.com/pythonutilities/jinjasql/blob/0.1.11/setup.py

Actions:
1. Create a brand new feedstock
2. Add a test suite

Notes:
- `jinjasql` is no longer maintained, see https://github.com/sripathikrishnan/jinjasql/issues/50#issuecomment-1657230029, but the fork `jinjasql2` is actively maintained (see https://github.com/pythonutilities/jinjasql) and we build `jinjasql2`

### CODE REVIEW

**Review by M-Waszkiewicz-Anaconda — COMMENTED** [review]
shall we take the url from https://pypi.org/project/jinjasql2/ ?

**Comment by skupr-anaconda** [comment]
> shall we take the url from https://pypi.org/project/jinjasql2/ ?

Not now, because PyPi has the latest version 0.1.10 but we need 0.1.11, see also the reason behind it https://github.com/pythonutilities/jinjasql/issues/15

**Review by lorepirri — APPROVED** [review]
LGTM,
destination channel is SF, right?

**Comment by skupr-anaconda** [comment]
> LGTM, destination channel is SF, right?

Yes

**Review by M-Waszkiewicz-Anaconda — APPROVED** [review]
LGTM

**Pull request merged**
